// This file is auto-generated by @hey-api/openapi-ts

export const $HTTPValidationError = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const $IMPORTANCE = {
    type: 'integer',
    enum: [0, 1, 2, 3],
    title: 'IMPORTANCE'
} as const;

export const $PaginateModel_Todo_ = {
    properties: {
        page: {
            type: 'integer',
            title: 'Page'
        },
        per_page: {
            type: 'integer',
            title: 'Per Page'
        },
        total_items: {
            type: 'integer',
            title: 'Total Items'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/app__main__Todo'
            },
            type: 'array',
            title: 'Items'
        }
    },
    type: 'object',
    required: ['page', 'per_page', 'total_items', 'items'],
    title: 'PaginateModel[Todo]'
} as const;

export const $PkOnlyTodofmdnkq = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        }
    },
    type: 'object',
    title: 'PkOnlyTodofmdnkq'
} as const;

export const $PkOnlyUsergijmjy = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        }
    },
    type: 'object',
    title: 'PkOnlyUsergijmjy'
} as const;

export const $TodoDto = {
    properties: {
        item: {
            type: 'string',
            title: 'Item'
        },
        plan_time: {
            type: 'string',
            title: 'Plan Time'
        },
        user_id: {
            type: 'integer',
            title: 'User Id'
        },
        content: {
            type: 'string',
            title: 'Content'
        },
        importance: {
            '$ref': '#/components/schemas/IMPORTANCE'
        }
    },
    type: 'object',
    required: ['item', 'plan_time', 'user_id', 'content', 'importance'],
    title: 'TodoDto'
} as const;

export const $UpdateTodoDto = {
    properties: {
        item: {
            type: 'string',
            title: 'Item'
        },
        plan_time: {
            type: 'string',
            title: 'Plan Time'
        },
        content: {
            type: 'string',
            title: 'Content'
        },
        importance: {
            '$ref': '#/components/schemas/IMPORTANCE'
        }
    },
    type: 'object',
    required: ['item', 'plan_time', 'content', 'importance'],
    title: 'UpdateTodoDto'
} as const;

export const $User = {
    properties: {
        id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        user_name: {
            type: 'string',
            maxLength: 12,
            minLength: 3,
            title: 'User Name'
        },
        pwd: {
            type: 'string',
            maxLength: 12,
            minLength: 3,
            title: 'Pwd'
        },
        todo_list: {
            title: 'Todo List'
        }
    },
    type: 'object',
    required: ['user_name', 'pwd'],
    title: 'User',
    example: {
        id: 0,
        pwd: 'string',
        todo_list: [
            {
                content: 'string',
                create_time: 'datetime',
                id: 0,
                item: 'string',
                plan_time: 'datetime',
                user_id: 0
            }
        ],
        user_name: 'string'
    }
} as const;

export const $UserDto = {
    properties: {
        user_name: {
            type: 'string',
            title: 'User Name'
        },
        pwd: {
            type: 'string',
            title: 'Pwd'
        }
    },
    type: 'object',
    required: ['user_name', 'pwd'],
    title: 'UserDto'
} as const;

export const $ValidationError = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const $app__main__Todo = {
    properties: {
        id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        item: {
            type: 'string',
            maxLength: 1000,
            title: 'Item'
        },
        create_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Create Time',
            default: '2024-07-22T14:26:28.883587'
        },
        plan_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Plan Time'
        },
        content: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 5000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content'
        },
        user_id: {
            type: 'integer',
            title: 'User Id'
        },
        user: {
            title: 'User'
        },
        importance: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/IMPORTANCE'
                },
                {
                    type: 'null'
                }
            ],
            default: 0
        }
    },
    type: 'object',
    required: ['item', 'user_id'],
    title: 'Todo',
    example: {
        content: 'string',
        create_time: 'datetime',
        id: 0,
        item: 'string',
        plan_time: 'datetime',
        user: {
            id: 0,
            pwd: 'string',
            user_name: 'string'
        },
        user_id: 0
    }
} as const;

export const $ormar__models__helpers__relations__Todo = {
    properties: {
        id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        item: {
            type: 'string',
            maxLength: 1000,
            title: 'Item'
        },
        create_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Create Time',
            default: '2024-07-22T14:26:28.883587'
        },
        plan_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Plan Time'
        },
        content: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 5000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content'
        },
        user_id: {
            type: 'integer',
            title: 'User Id'
        },
        user: {
            title: 'User'
        },
        importance: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/IMPORTANCE'
                },
                {
                    type: 'null'
                }
            ],
            default: 0
        }
    },
    type: 'object',
    required: ['item', 'user_id'],
    title: 'Todo',
    example: {
        content: 'string',
        create_time: 'datetime',
        id: 0,
        item: 'string',
        plan_time: 'datetime',
        user: {
            id: 0,
            pwd: 'string',
            todo_list: [
                {
                    content: 'string',
                    create_time: 'datetime',
                    id: 0,
                    item: 'string',
                    plan_time: 'datetime',
                    user_id: 0
                }
            ],
            user_name: 'string'
        },
        user_id: 0
    }
} as const;