// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type OptionsLegacyParser } from '@hey-api/client-axios';
import type { GetProtectedProtectedGetData, GetProtectedProtectedGetError, GetProtectedProtectedGetResponse, LoginLoginPostData, LoginLoginPostError, LoginLoginPostResponse, RefreshRefreshPostError, RefreshRefreshPostResponse, CreateUserCreateUserPostData, CreateUserCreateUserPostError, CreateUserCreateUserPostResponse, CreateTagCreateTagPostData, CreateTagCreateTagPostError, CreateTagCreateTagPostResponse, CreateTodoCreateTodosPostData, CreateTodoCreateTodosPostError, CreateTodoCreateTodosPostResponse, ReadTodosGetTodosGetData, ReadTodosGetTodosGetError, ReadTodosGetTodosGetResponse, DeleteTodosDeleteTodosTodoIdDeleteData, DeleteTodosDeleteTodosTodoIdDeleteError, DeleteTodosDeleteTodosTodoIdDeleteResponse, DeleteTagsDeleteTagTagIdDeleteData, DeleteTagsDeleteTagTagIdDeleteError, DeleteTagsDeleteTagTagIdDeleteResponse, UpdateTodosUpdateTodosTodoIdPostData, UpdateTodosUpdateTodosTodoIdPostError, UpdateTodosUpdateTodosTodoIdPostResponse, GetUserByTodoGetUserByTodoTodoIdGetData, GetUserByTodoGetUserByTodoTodoIdGetError, GetUserByTodoGetUserByTodoTodoIdGetResponse, ReadTodosByUserGetTodosByUserUserIdGetData, ReadTodosByUserGetTodosByUserUserIdGetError, ReadTodosByUserGetTodosByUserUserIdGetResponse, GetTodosByItemNameGetTodosByItemNameGetData, GetTodosByItemNameGetTodosByItemNameGetError, GetTodosByItemNameGetTodosByItemNameGetResponse, GetTagsByUserGetTagsByUserGetData, GetTagsByUserGetTagsByUserGetError, GetTagsByUserGetTagsByUserGetResponse, GetTodosByImportanceGetTodosByItemImportanceItemImportanceGetData, GetTodosByImportanceGetTodosByItemImportanceItemImportanceGetError, GetTodosByImportanceGetTodosByItemImportanceItemImportanceGetResponse, GetTodoByTodoIdGetTodoByTodoIdTodoIdGetData, GetTodoByTodoIdGetTodoByTodoIdTodoIdGetError, GetTodoByTodoIdGetTodoByTodoIdTodoIdGetResponse, GetTodoByPlanTimeGetTodosByPlanTimePlanTimeStrGetData, GetTodoByPlanTimeGetTodosByPlanTimePlanTimeStrGetError, GetTodoByPlanTimeGetTodosByPlanTimePlanTimeStrGetResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Get Protected
 */
export const getProtectedProtectedGet = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<GetProtectedProtectedGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetProtectedProtectedGetResponse, GetProtectedProtectedGetError, ThrowOnError>({
        ...options,
        url: '/protected'
    });
};

/**
 * Login
 */
export const loginLoginPost = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<LoginLoginPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<LoginLoginPostResponse, LoginLoginPostError, ThrowOnError>({
        ...options,
        url: '/login'
    });
};

/**
 * Refresh
 */
export const refreshRefreshPost = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).post<RefreshRefreshPostResponse, RefreshRefreshPostError, ThrowOnError>({
        ...options,
        url: '/refresh'
    });
};

/**
 * Create User
 */
export const createUserCreateUserPost = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<CreateUserCreateUserPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateUserCreateUserPostResponse, CreateUserCreateUserPostError, ThrowOnError>({
        ...options,
        url: '/create_user/'
    });
};

/**
 * Create Tag
 */
export const createTagCreateTagPost = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<CreateTagCreateTagPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateTagCreateTagPostResponse, CreateTagCreateTagPostError, ThrowOnError>({
        ...options,
        url: '/create_tag/'
    });
};

/**
 * Create Todo
 */
export const createTodoCreateTodosPost = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<CreateTodoCreateTodosPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateTodoCreateTodosPostResponse, CreateTodoCreateTodosPostError, ThrowOnError>({
        ...options,
        url: '/create_todos/'
    });
};

/**
 * Read Todos
 */
export const readTodosGetTodosGet = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<ReadTodosGetTodosGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<ReadTodosGetTodosGetResponse, ReadTodosGetTodosGetError, ThrowOnError>({
        ...options,
        url: '/get_todos/'
    });
};

/**
 * Delete Todos
 */
export const deleteTodosDeleteTodosTodoIdDelete = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<DeleteTodosDeleteTodosTodoIdDeleteData, ThrowOnError>) => {
    return (options?.client ?? client).delete<DeleteTodosDeleteTodosTodoIdDeleteResponse, DeleteTodosDeleteTodosTodoIdDeleteError, ThrowOnError>({
        ...options,
        url: '/delete_todos/{todo_id}'
    });
};

/**
 * Delete Tags
 */
export const deleteTagsDeleteTagTagIdDelete = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<DeleteTagsDeleteTagTagIdDeleteData, ThrowOnError>) => {
    return (options?.client ?? client).delete<DeleteTagsDeleteTagTagIdDeleteResponse, DeleteTagsDeleteTagTagIdDeleteError, ThrowOnError>({
        ...options,
        url: '/delete_tag/{tag_id}'
    });
};

/**
 * Update Todos
 */
export const updateTodosUpdateTodosTodoIdPost = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<UpdateTodosUpdateTodosTodoIdPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<UpdateTodosUpdateTodosTodoIdPostResponse, UpdateTodosUpdateTodosTodoIdPostError, ThrowOnError>({
        ...options,
        url: '/update_todos/{todo_id}'
    });
};

/**
 * Get User By Todo
 */
export const getUserByTodoGetUserByTodoTodoIdGet = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetUserByTodoGetUserByTodoTodoIdGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetUserByTodoGetUserByTodoTodoIdGetResponse, GetUserByTodoGetUserByTodoTodoIdGetError, ThrowOnError>({
        ...options,
        url: '/get_user_by_todo/{todo_id}'
    });
};

/**
 * Read Todos By User
 */
export const readTodosByUserGetTodosByUserUserIdGet = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<ReadTodosByUserGetTodosByUserUserIdGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<ReadTodosByUserGetTodosByUserUserIdGetResponse, ReadTodosByUserGetTodosByUserUserIdGetError, ThrowOnError>({
        ...options,
        url: '/get_todos_by_user/{user_id}'
    });
};

/**
 * Get Todos By Item Name
 * Get todos by the item name
 */
export const getTodosByItemNameGetTodosByItemNameGet = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetTodosByItemNameGetTodosByItemNameGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetTodosByItemNameGetTodosByItemNameGetResponse, GetTodosByItemNameGetTodosByItemNameGetError, ThrowOnError>({
        ...options,
        url: '/get_todos_by_item_name/'
    });
};

/**
 * Get Tags By User
 * Get tag by the user
 */
export const getTagsByUserGetTagsByUserGet = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetTagsByUserGetTagsByUserGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetTagsByUserGetTagsByUserGetResponse, GetTagsByUserGetTagsByUserGetError, ThrowOnError>({
        ...options,
        url: '/get_tags_by_user/'
    });
};

/**
 * Get Todos By Importance
 * Get todos by the item importance
 */
export const getTodosByImportanceGetTodosByItemImportanceItemImportanceGet = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetTodosByImportanceGetTodosByItemImportanceItemImportanceGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetTodosByImportanceGetTodosByItemImportanceItemImportanceGetResponse, GetTodosByImportanceGetTodosByItemImportanceItemImportanceGetError, ThrowOnError>({
        ...options,
        url: '/get_todos_by_item_importance/{item_importance}'
    });
};

/**
 * Get Todo By Todo Id
 * Get todo by the todo_id
 */
export const getTodoByTodoIdGetTodoByTodoIdTodoIdGet = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetTodoByTodoIdGetTodoByTodoIdTodoIdGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetTodoByTodoIdGetTodoByTodoIdTodoIdGetResponse, GetTodoByTodoIdGetTodoByTodoIdTodoIdGetError, ThrowOnError>({
        ...options,
        url: '/get_todo_by_todo_id/{todo_id}'
    });
};

/**
 * Get Todo By Plan Time
 * Get todos by the plan time
 */
export const getTodoByPlanTimeGetTodosByPlanTimePlanTimeStrGet = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetTodoByPlanTimeGetTodosByPlanTimePlanTimeStrGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetTodoByPlanTimeGetTodosByPlanTimePlanTimeStrGetResponse, GetTodoByPlanTimeGetTodosByPlanTimePlanTimeStrGetError, ThrowOnError>({
        ...options,
        url: '/get_todos_by_plan_time/{plan_time_str}'
    });
};